spring:
  datasource:
    url: jdbc:mysql://localhost:3306/electriccharge?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

yiming1234:
  electric:
    building-code:
    floor-code:
    room-code:

  wechat:
    appid:
    appsecret:

  mail:
    from:
    username:
    password:
