server:
  port: 8080

spring:
  profiles:
    active: template

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: cn.yiming1234.electriccharge.entity
    configuration:
      map-underscore-to-camel-case: true

yiming1234:
  wechat:
    appid: ${yiming1234.wechat.appid}
    secret: ${yiming1234.wechat.secret}

  electric:
    area-id: 2307499265384382465
    building-code: ${yiming1234.electric.building-code}
    floor-code: ${yiming1234.electric.floor-code}
    room-code: ${yiming1234.electric.room-code}
    cookie: ${yiming1234.electric.cookie}

  mail:
    host: smtp.qq.com
    port: 465
    subject: 寝室电费欠费提醒
    from: ${yiming1234.mail.from}
    username: ${yiming1234.mail.username}
    password: ${yiming1234.mail.password}