server:
  port: 8080

spring:
  profiles:
    active: dev, common

yiming1234:
  server:
    host: ${yiming1234.server.host}
  wechat:
    appid: ${yiming1234.wechat.appid}
    secret: ${yiming1234.wechat.secret}

  electric:
    cookie: ${yiming1234.electric.cookie}

  mail:
    host: ${yiming1234.mail.host}
    port: ${yiming1234.mail.port}
    from: ${yiming1234.mail.from}
    subject: ${yiming1234.mail.subject}