name: SpringBoot Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - './**'

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Maven Settings XML
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: ''
        servers: ''

    - name: Build with Maven
      run: mvn package -B -DskipTests --file ./pom.xml

    - name: GH Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./target/electricCharge-*.jar
        tag_name: electricCharge-v1.0

    - name: Log in to GitHub Docker Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -f src/main/docker/Dockerfile -t ghcr.io/comppsyunion/comppsyunion/electriccharge:latest .

    - name: Push Docker image to GitHub Packages
      run: |
        docker push ghcr.io/comppsyunion/comppsyunion/electriccharge:latest
